name:                identicon
version:             0.1.0.0
github:              "githubuser/identicon"
license:             BSD3
author:              "rabogaa"
maintainer:          "rabogaa+github@innovuze.com"
copyright:           "2018 rabogaa"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rabogaa/hidenticon#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  identicon-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - identicon

tests:
  identicon-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - identicon
